name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v4
      - name: cek lokasi current dir
        run: pwd
      - name: cek versi python
        run: python --version
      - name: running sample.py
        run: python sample.py
      - name: cek veri server
        run: neofetch
        
        
      
